Project/Library/urls.py
from django.urls import path
from .views import register, loginPage, logoutUser, deleteUser, livroCreateView, livrosListView, livroUpdateView, livroDeleteView

app_name = "livros"

urlpatterns = [
    path('register/', register, name="register"),
    path('login/', loginPage, name="login"),
    path('logout/', logoutUser, name='logout'),
    path('delete/', deleteUser, name='delete'),

    path('', livrosListView, name='home-livros'),
    path('cria/', livroCreateView, name='cria-livros'),
    path('atualiza/<int:pk>/', livroUpdateView, name='atualiza-livro'),
    path('apaga/<int:pk>/', livroDeleteView, name='apaga-livro'),
]

Project/Project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Library.urls')),
    path('results', include('Library.urls')),
    path('login', include('Library.urls')),
    path('logout', include('Library.urls')),
    path('delete', include('Library.urls')),
    path('validateUsername', include('Library.urls')),
]

Project/Library/models.py
from django.db import models

# Create your models here.

class User(models.Model):
    name = models.CharField("Name", max_length=80)
    email = models.CharField("Email", max_length=80)
    password = models.CharField("Password", max_length=20)


class Livros(models.Model):
    name = models.CharField('Título', max_length=100)
    author = models.CharField('Autor(a)', max_length=200)
    publishingHouse = models.CharField('Editora', max_length=200)
    readStatus = models.BooleanField('Status de Lido', blank='False')
    review = models.IntegerField('Review', help_text='Entre a nota - 0 a 5 (Para não lidos, entre 0)')
    year = models.IntegerField('Ano Lido/Adicionado')


    def __str__(self):
        return self.nome

class Request(models.Model):
    name = models.CharField('Name', max_length=100)
    author = models.CharField('Author', max_length=200)
    base_url = models.CharField('URL', max_length=200)

    def __str__(self):
        return self.nome

Project/Library/forms.py
from .models import Livros
from django import forms
from .models import User


class UserModel2Form(forms.ModelForm):
    class Meta:
        model = User
        fields = '__all__'


class LivrosModel2Form(forms.ModelForm):
    class Meta:
        model = Livros
        fields = '__all__'

Project/Library/views.py
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from django.http.response import HttpResponseRedirect
from django.urls.base import reverse_lazy
from .models import Request
from django.http import JsonResponse
from django.contrib.auth.forms import UserCreationForm
from .forms import LivrosModel2Form
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from .models import Livros


def livrosListView(request):
    if request.method == 'GET':
        livros = Livros.objects.all()
        context = {'livros': livros, }
        return render(
            request,
            'livros/listaLivros.html',
            context)



def livroCreateView(request):
    if request.method == 'GET':
        context = { 'formulario': LivrosModel2Form, }
        return render(request,
        "livros/criaLivros.html", context)

    elif request.method == 'POST':
        formulario = LivrosModel2Form(request.POST)
        if formulario.is_valid():
            livro = formulario.save()
            livro.save()
            return redirect("/")


def livroUpdateView(request, pk):
    if request.method == 'GET':
        livro = Livros.objects.get(pk=pk)
        formulario = LivrosModel2Form(instance=livro)
        context = {'livro': formulario, }
        return render(request, 'livros/atualizaLivro.html', context)
    elif request.method == 'POST':
        livro = get_object_or_404(Livros, pk=pk)
        formulario = LivrosModel2Form(request.POST, instance=livro)
        if formulario.is_valid():
            livro = formulario.save()
            livro.save()
            return redirect("/")
        else:
            context = {'livro': formulario, }
            return render(request, 'livros/atualizaLivro.html', context)


def livroDeleteView(request, pk):
    if request.method == 'GET':
        livro = Livros.objects.get(pk=pk)
        context = {'livro': livro, }
        return render(
        request, 'livros/apagaLivro.html',
        context)
    elif request.method == 'POST':
        livro = Livros.objects.get(pk=pk)
        livro.delete()
        print("Removendo o livro", pk)
        return redirect("/")


def register(request):
    if request.method == 'POST':
        # cria um usuário
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request, 'Conta criada para usuário: ' + user)
            return redirect("/login/")
        else:
            context = {
                'form': form,
            }
            return render(request, 'accounts/register.html', context)
    else:
        # mostra o formulário
        form = UserCreationForm()
        context = {'form': form, }
        return render(request, 'accounts/register.html', context)


def loginPage(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("/")
        else:
            messages.info(request, "Usuário ou senha estão incorretos!")
            return render(request, "accounts/login.html")
    return render(request, "accounts/login.html")


def deleteUser(request):
    if request.method == 'POST':
        try:
            username = request.POST.get('username')
            print(username)
            u = User.objects.get(username=username)
            u.delete()
        except:
            messages.error(request, f"Failed to delete user!")
            return render(request, "accounts/delete.html")
        return redirect("/")
    else:
        return render(request, 'accounts/delete.html')


def logoutUser(request):
    logout(request)
    return redirect("/")

Project/Library/templates/accounts/delete.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>Excluir Usuário</title>
    <link rel="stylesheet" href="{% static 'account.css' %}">
</head>
<body>


    <div class="container">
      <div class="card">
        <form class="box"method="post">
            {% csrf_token %}
          <p class="text-muted"> Excluir usuário</p>
          <input type="text" placeholder="Usuário" name="username"/>
          <input type="submit" value="Excluir"></input>
        </form>
      </div>
    </div>



<script>

        $('.message a').click(function(){
        $('form').animate({height: "toggle", opacity: "toggle"}, "slow");
        });

</script>






</body>
</html>

Project/Library/templates/accounts/login.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <title>Login</title>
  <link rel="stylesheet" href="{% static 'account.css' %}">
</head>

<body>

  <div class="container">
    <div class="card">
      <form class="box" method="post">
        <h1>Login</h1>
        {% csrf_token %}
        <p class="text-muted"> Entre com seu usuário e senha</p>
        <input type="text" placeholder="Usuário" name="username" id="id_username" onfocusout="Request();" />
        <input type="password" placeholder="Senha" name="password" />
        <p id="erroCadastro"></p>
        <input type="submit" value="Entrar"></input>
        <p class="text-muted">Não possui conta? <a href="/register">Crie uma conta</a></p>
      </form>
    </div>
  </div>



  <script>
    function Request() {
      document.getElementById("erroCadastro").innerHTML = ""
      var campoUsername = document.getElementById('id_username');
      fetch(url)
        .then(resposta => resposta.json())
        .then(data => mostrarResposta(data))
        .catch(erro => console.error(erro));
    }

    function mostrarResposta(data) {
      if (!data.existe) {
        document.getElementById("erroCadastro").innerHTML = "usuário não cadastrado"
      }
    }

    $('.message a').click(function () {
      $('form').animate({
        height: "toggle",
        opacity: "toggle"
      }, "slow");
    });
  </script>






</body>

</html>

Project/Library/templates/accounts/register.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>Registrar</title>
    <link rel="stylesheet" href="{% static 'account.css' %}">
</head>
<body>


    <div class="container">
      <div class="card">
        <form class="box"method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <input type="submit" value="Criar conta"></input>
          <p class="text-muted">Já possui conta? <a href="/login/">Login</a></p>
        </form>
      </div>
    </div>



<script>

        $('.message a').click(function(){
        $('form').animate({height: "toggle", opacity: "toggle"}, "slow");
        });

</script>






</body>
</html>

Project/Library/templates/livros/apagaLivro.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>Exclui Livro</title>
    <link rel="stylesheet" href="{% static 'default.css' %}">
</head>

<body>
    {% include 'livros/links.html' %}
    <div class="container">
        <form class="card" method="post">
            {% csrf_token %}
            <p class="text-muted"> Confirma a exclusão de {{livro.name}}?</p>
            <input type="submit" value="Excluir">
        </form>
        <button id="cancelButton">Cancelar</button>
    </div>
</body>

</html>

<script type="text/javascript">
    document.getElementById("cancelButton").onclick = function () {
        location.href = "/";
    };
</script>

Project/Library/templates/livros/atualizaLivro.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>Atualiza Livro</title>
    <link rel="stylesheet" href="{% static 'admin.css' %}">
</head>

<body>
    {% include 'livros/links.html' %}
        <h1>Atualização de livro</h1>
        <form class="card" method="post">
            {% csrf_token %}
            <table type="admin">
                {{ livro.as_table }}
            </table>
            <input type="submit" value="Atualizar">
        </form>
        <button id="cancelButton">Cancelar</button>
</body>

</html>

<script type="text/javascript">
    document.getElementById("cancelButton").onclick = function () {
        location.href = "/";
    };
</script>

Project/Library/templates/livros/criaLivros.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>Adicionar Livro</title>
    <link rel="stylesheet" href="{% static 'admin.css' %}">
</head>

<body>
    {% include 'livros/links.html' %}
        <h1>Adicionar Livro</h1>
        <form class="card" method="post">
            {% csrf_token %}
            <table type="admin">
                {{ formulario.as_table }}
            </table>
            <input type="submit" value="Adicionar">
        </form>
        <button id="cancelButton">Cancelar</button>
</body>

</html>

<script type="text/javascript">
    document.getElementById("cancelButton").onclick = function () {
        location.href = "/";
    };
</script>

Project/Library/templates/livros/links.html
<!-- Para incluir esse fragmento de página HTML em uma página HTML use: { % include 'livros/links.html' % } -->
{% load static %}
<link rel="stylesheet" href="{% static 'links.css' %}">
<div class="box">
    <nav class="navMenu">
        <a href="/">Home</a>
        {% if user.is_authenticated %}
        {% block content %}
        <a href="{% url 'livros:cria-livros' %}">Adicionar</a>
        <a href="logout/">Sair</a>
        {% endblock %}
        {% else %}
        <a href="login/">Entrar</a>
        {% endif %}
        <div class="dot"></div>
    </nav>
</div>

Project/Library/templates/livros/listaLivros.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>Lista Livros</title>
    <link rel="stylesheet" href="{% static 'default.css' %}">
</head>

<body>
    {% include 'livros/links.html' %}
    <div class="container">
        <h1 class="container">Seus Livros</h1>
        <table>
            <tr>
                <th>Título</th>
                <th>Autor(a)</th>
                <th>Editora</th>
                <th>Lido?</th>
                <th>Review _/5</th>
                <th>Ano</th>
                <th>Ações disponíveis</th>
            </tr>
            {% for livro in livros %}
            <tr>
                <td>{{livro.name}}</td>
                <td>{{livro.author}}</td>
                <td>{{livro.publishingHouse}}</td>
                <td>{{livro.readStatus}}</td>
                <td>{{livro.review}}</td>
                <td>{{livro.year}}</td>
                <td>
                    {% if user.is_authenticated %}
                    {% block content %}
                    <a href="{% url 'livros:atualiza-livro' pk=livro.id %}">Atualizar |
                        <a href="{% url 'livros:apaga-livro' pk=livro.id%}">Excluir</a></a>
                    {% endblock %}
                    {% else %}
                    <p>Faça o Login para realizar ações</p>
                    {% endif %}
                </td>
            </tr>
            {% empty %}
            <tr>
                <th colspan="5">Ainda não tem livros cadastrados</th>
            </tr>
            {% endfor %}
        </table>
    </div>
</body>

</html>